import { Application, json, urlencoded } from "express";
import morgan from "morgan";
import cors from "cors";
import helmet from "helmet";
import cookieParser from "cookie-parser";
import asyncError from "./errors.middleware";
import indexRoutes from "../routes/index.routes";
import database from "../configs/database.config";
import dotenv from "dotenv";
database();
dotenv.config();
export default (app: Application) => {
  app.use(morgan('dev'));
  app.use(cors());
  app.use(json());
  app.use(helmet());
  app.use(cookieParser());
  app.use(urlencoded());
  app.use(asyncError);
  indexRoutes(app);
};